# Generated by Django 3.0.8 on 2020-07-26 16:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('authors', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), size=None)),
                ('publisher', models.CharField(max_length=120)),
                ('publication_date', models.DateField()),
                ('link', models.CharField(max_length=120)),
                ('cover_image', models.ImageField(upload_to='')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
